GamesDetails <-function() {  
  requestor.games <- ftable(db.games.dt)$select(
                                user_id = requestor,
                                partner_id = requestee,
                                game_id = id,
                                user_quiz_done = requestor_quiz_done,
                                partner_quiz_done = requestee_quiz_done,
                                user_finished = requestor_finished,
                                partner_finished = requestee_finished,
                                game_finished = !is.na(finished_date),
                                requestor = TRUE,
                                request_date = request_date,  
                                user_skill = requestor_skill,
                                partner_skill = requestee_skill,
                                response = response,
                                course_id = course,	
                                user_quiz_id = requestor_quiz,
                                partner_quiz_id = requestee_quiz,
                                user_student_points = requestor_student_points,	
                                user_teacher_points = requestor_teacher_points,
                                partner_student_points = requestee_student_points,  
                                partner_teacher_points = requestee_teacher_points,	
                                finished_date = finished_date)$dt
  
  requestee.games <- ftable(db.games.dt)$select(
                                user_id = requestee,
                                partner_id = requestor,
                                game_id = id,
                                user_quiz_done = requestee_quiz_done,
                                partner_quiz_done = requestee_quiz_done,
                                user_finished = requestee_finished,
                                partner_finished = requestor_finished,
                                game_finished = !is.na(finished_date),
                                requestor = FALSE,
                                request_date = request_date,  
                                user_skill = requestee_skill,
                                partner_skill = requestor_skill,
                                response = response,
                                course_id = course,  
                                user_quiz_id = requestee_quiz,
                                partner_quiz_id = requestor_quiz,
                                user_student_points = requestee_student_points,	
                                user_teacher_points = requestee_teacher_points,
                                partner_student_points = requestor_student_points,  
                                partner_teacher_points = requestor_teacher_points,	
                                finished_date = finished_date)$dt
  
  game.details <- ftable(requestor.games)$union(requestee.games)$dt
}
